<html lang="en"><head><title>HAPEE Home</title><meta name="viewport" content="width=device-width, initial-scale=1"/><link rel="icon" href="/images/haproxy-icon.svg"/><link rel="stylesheet" href="/css/custom.css"/><link rel="stylesheet" href="/css/styles.css"/><script src="/js/colormode.js"></script><script src="/js/popper.min.js"></script><script src="/js/bootstrap.min.js"></script><script src="/js/apicrud.js"></script></head>
<body>
<div class="container py-4">
<h2 class="text-center">418 I'm a teapot</h2>
<figure class="text-center">
  <blockquote class="blockquote">
    <a href="/tea"><img src="/images/teapot.svg" class="w-50"/></a>
    <p>Sorry, I can't help you, I'm a teapot</p>
  </blockquote>
  <figcaption class="blockquote-footer">
    Hyper Text Coffee Pot Control Protocol <cite title="Source"> rfc2324</cite>
  </figcaption>
</figure
</div>
</body>
</html>
